PROJECT = main
# Project files
PROJECT_PATH = .
PROJECT_OBJS = $(PROJECT).o board.o uart.o uECC.o sha256.o aes.o 3des.o printString.o led.o button.o testLPM.o testECC.o testSHA256.o testAES.o test3DES.o testSignal.o testUtils.o

BUILD_DIR = build

LIBRARY_OBJS_FIN=

include ../Makefile.include	
